export const UPDATE_VALIDATITON = 'UPDATE_VALIDATITON';
export const ADD_VALIDATE_COLORS = 'ADD_VALIDATE_COLORS';
export const DELETE_VALIDATE_COLORS = 'DELETE_VALIDATE_COLORS';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const ADD_IMAGE = 'ADD_IMAGE';
export const INVALID_IMAGES = 'INVALID_IMAGES';
