export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
export const VALIDATE_IMAGES = 'VALIDATE_IMAGES';
export const UPDATE_VALIDATITON = 'UPDATE_VALIDATITON';
export const ADD_VALIDATE_COLORS = 'ADD_VALIDATE_COLORS';
export const DELETE_VALIDATE_COLORS = 'DELETE_VALIDATE_COLORS';
